say verb support play audio in array
jambonz/jambonz-feature-server pull request #482
Opened 2023-10-12 11:22 UTC by xquanluu

https://github.com/jambonz/jambonz-feature-server/issues/472

2023-10-12 13:54 UTC, davehorton requested changes

2023-10-12 13:54 UTC, davehorton commented on lib/tasks/say.js
> +      const arr = this.text.map((t) => {
could we just make this
```
const arr = this.text.map((t) => this._validateURL(t) ? t : generateAudio(t);
```

2023-10-12 14:37 UTC, davehorton commented
could you add a test case showing an array of mixed text and http urls to say

2023-10-19 18:46 UTC, davehorton commented on lib/tasks/say.js
> +      const arr = this.text.map((t) => {
@xquanluu ?

2023-10-19 23:11 UTC, xquanluu commented on lib/tasks/say.js
> +      const arr = this.text.map((t) => {
fixed

2023-10-19 23:12 UTC, xquanluu commented
added testcase.

2023-10-20 06:14 UTC, davehorton approved these changes

2023-10-20 06:14 UTC, merged