rest:dial: Support sipindialog hook
jambonz/jambonz-feature-server pull request #531
Opened 2023-11-13 13:59 UTC by avoylenko

I want to receive the sip indialog messages(INFO,  MESSAGE) when placing an outbound call from JBZ system using `createCall` api. At this moment, I have failed to find inbox solution thats why pushing this PR. Awaiting your comments.

fyi: verb specification must be updated accordingly to support new property.

2023-11-13 14:26 UTC, davehorton requested changes

2023-11-13 14:26 UTC, davehorton commented on lib/tasks/rest_dial.js
> +  _initSipIndialogRequestListener(cs, dlg) {
please change the name to `_initSipRequestWithinDialogHandler`

2023-11-13 14:26 UTC, davehorton commented
also, please make a companion PR to verb-speciifications

2023-11-13 15:24 UTC, avoylenko commented
> also, please make a companion PR to verb-speciifications

verb specification https://github.com/jambonz/verb-specifications/pull/34

2023-11-13 15:25 UTC, avoylenko commented
Also the swagger specification will be updated if this PR suits the platform requirements.

2023-11-14 14:16 UTC, davehorton approved these changes

2023-11-14 14:16 UTC, merged