fix pause resume background transcribe
jambonz/jambonz-feature-server pull request #586
Opened 2023-12-29 08:27 UTC by xquanluu

2023-12-29 08:35 UTC, xquanluu commented
Tested on jambonz.me

2023-12-29 12:32 UTC, davehorton requested changes

2023-12-29 12:32 UTC, davehorton commented on lib/session/call-session.js
> +      this.logger.info('CallSession:_lccTranscribeStatus - there is no background transcribe task');
this will be by far the common case, and no need to log any thing

2024-02-12 15:25 UTC, davehorton commented
@xquanluu should we merge this?

2024-02-12 15:27 UTC, xquanluu commented
Yes, I tested this.

The question for you is should we allow LCC transcribe_status be able to stop both background transcribe and foreground transcribe together.

2024-02-12 15:29 UTC, davehorton commented
> Yes, I tested this.
> 
> The question for you is should we allow LCC transcribe_status be able to stop both background transcribe and foreground transcribe together.

So right now it only pauses the background transcribe, right?

2024-02-12 15:31 UTC, xquanluu commented
> > Yes, I tested this.
> > The question for you is should we allow LCC transcribe_status be able to stop both background transcribe and foreground transcribe together.
> 
> So right now it only pauses the background transcribe, right?

Right now, it's only pauses the foreground transcribe

2024-02-12 15:33 UTC, davehorton commented
ah, ok I see.  Well, I think we should wait on this PR until we can make it pause both/all transcribes.  I think the common use case is that some PII data is being spoken and we wouldn't want it to appear on any transcripts

2024-02-12 15:37 UTC, xquanluu commented
I see, If that's the case then the PR is ready for merging, this PR will pause and resume both background and foreground transcribe

2024-02-12 15:38 UTC, merged