Feat/864: bargeIn and VAD at config level fix
jambonz/jambonz-feature-server pull request #889
Opened 2024-09-04 08:43 UTC by rammohan-y

Fixed the issue of bargeIn with VAD at config level

2024-09-05 13:55 UTC, rammohan-y commented
The following test cases are tested with this change

gather verb with minBargeinWordCount = 0 and vad defined: vad is enabled
gather verb with minBargeinWordCount = 0 and vad un-defined: vad is enabled with default sensitivity 2
gather verb with vad defined and minBargeinWordCount not defined: vad is enabled
gather verb with minBargeinWordCount > 0 : same as existing behavior

bargeIn config with minBargeinWordCount = 0 vad is not defined: vad is enabled with default sensitivity 2
bargeIn config with minBargeinWordCount > 0: same as existing behavior
In config only vad is defined and bargeIn config not defined: vad is enabled by setting minBargeinWordCount as 0

2024-09-10 08:05 UTC, vdharashive commented
@davehorton @xquanluu can this be reviewed

2024-09-12 13:26 UTC, xquanluu commented on lib/tasks/config.js
> +      cs.bargeIn = this.bargeIn;
how do I reset bargeIn from call session level after bargeIn is set?

2024-09-12 13:28 UTC, xquanluu commented on lib/tasks/gather.js
> +    if (this.data.minBargeinWordCount !== undefined) {
if (this.bargeIn.minBargeinWordCount)

is much better

2024-09-13 02:36 UTC, xquanluu commented
Hi @rammohan-y 

https://github.com/jambonz/verb-specifications/blob/main/specs.json#L62

from this specification, the vad has its own properties to enable and disable, we cannot use minBargeinWordCount to enable or disable the vad, Could you please rethink to use vad object in config for your application.

This PR is invalid to me.

2024-09-13 02:37 UTC, xquanluu requested changes
invalid PR

2024-09-13 10:37 UTC, closed without merging